### ISSUE TITLE
Issues with tutorial ListCurrentEmacsBuffersAndSizesInBarChart.org

### ISSUE THREAD

**Issue by DamienCassou** [ag91/moldable-emacs#12]
> invoke M-x and type me/mold

I guess it is `me-mold` instead

> type “Playground” 

I get

```
Warning (emacs): Mold nil has no examples! Would you mind to add one?
You can use TODO now to add the last usage as an example
```

and no buffer opens. After reading the README, I realize I needed to do `(me-setup-molds)`. You might want to repeat it in the tutorial if it is meant for new users.

> type “PlistToBarChart” and hit return 

I get an error about missing `csv-mode`. You might want to add csv-mode to prerequisites.

**Comment by DamienCassou** [comment]
Then I got

> graph --bar --figsize 2560x1080 --xtick-angle 90 /tmp/somefile.csv: exited abnormally with code 1.

Executing that in a terminal reveals an [issue with graph](https://github.com/mcastorina/graph-cli/issues/24).

**Comment by ag91** [comment]
@DamienCassou can I close this or do I need to improve something? 
(Maybe you could suggest another software for plotting that is as easy to use as graph-cli?)

**Comment by DamienCassou** [comment]
I'm closing the issue. Thank you for having worked on it.
