### ISSUE TITLE
I wanted to comment about an article, Moldable Emacs: let's make English easy to query!

### ISSUE THREAD

**Issue by wereket** [ag91/moldable-emacs#17]
Hello
After reading Moldable Emacs: let's make English easy to query, I wanted to point a blog,
https://mullikine.github.io/ with great articles like https://mullikine.github.io/posts/review-of-the-case-for-learned-index-structures/ etc.
The author of the blog has a great package maybe you know already 
https://github.com/semiosis/pen.el
Thanks for your time

**Comment by ag91** [comment]
Ah thanks! I think the author has a talk at EmacsConf this year: looking
forward to watch it. I never used GTP before, but I will look into it: thanks!
