### ISSUE TITLE
Some links about moldable development

### ISSUE THREAD

**Issue by DamienCassou** [ag91/moldable-emacs#29]
I just found a few more resources about moldable development that you may like:

- [introducing Lepiter](https://lepiter.io/feenk/introducing-lepiter--knowledge-management--e2p6apqsz5npq7m4xte0kkywn/)
- [demo+interview of Tudor Gîrba at InfoQ](https://www.infoq.com/presentations/moldable-development)
- [other interview of Tudor Gîrba at InfoQ](https://www.infoq.com/podcasts/tudor-girba-moldable-development)

**Comment by ag91** [comment]
Thanks Damien, I indeed missed these :D 
I also like: https://tube.switch.ch/videos/326a1304 and the Hitchicker series https://www.youtube.com/watch?v=5s5x2pzh-CM&list=PLfrs5bwLJOoBtfhXJ4mqcQ4ktpQOEBTvP
Tudor is a smart person
